name : MonoRepo CI/CD
on:
  push:

  pull_request:
    branches:
      - main

jobs :
  flutter_build:
    name: Run Flutter build clean
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
      - uses: subosito/flutter-action@v2
        with:
          java-version: 'x.x'
      # - run: export PATH="$PATH:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools/bin"
      - run: flutter pub global activate melos
      - run: flutter pub global run melos bootstrap

  # flutter_test:
  #   name: Run Flutter app tests
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: 'x.x'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #     - run: flutter pub get
   
  #     # - run: flutter analyze
  #     - run: flutter test          
