name : MonoRepo CI/CD
on:
  push:

  pull_request_target:
    branches:
      - main
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
jobs :
  # flutter_build:
  #   name: Run Flutter build clean
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: subosito/flutter-action@v2
  #     - run: echo "${RUNNER_TEMP}/flutter/bin" ${RUNNER_TEMP}/flutter/.pub-cache/bin  >> $GITHUB_PATH
  #     - run: flutter pub global activate melos && flutter pub global run melos build:clean

  # flutter_test:
  #   name: Run Flutter app tests
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: 'x.x'
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #     - run: flutter pub global activate melos && flutter pub global run melos build:clean
  #      # - run: flutter analyze
  #     - run: melos test 
  automerge: 
    # needs : [flutter_test,flutter_build]
    runs-on: windows-latest
    steps:
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"



# name: automerge
# on:
#   pull_request:
#     types:
#       - labeled
#       - unlabeled
#       - synchronize
#       - opened
#       - edited
#       - ready_for_review
#       - reopened
#       - unlocked
#   pull_request_review:
#     types:
#       - submitted
#   check_suite:
#     types:
#       - completed
#   status: {}
# jobs:
#   automerge:
#     runs-on: ubuntu-latest
#     steps:
#       - id: automerge
#         name: automerge
#         uses: "pascalgn/automerge-action@v0.15.6"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

